# Generated by Django 5.0.4 on 2024-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_name_alter_meal_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Картинка'),
        ),
    ]
