# Generated by Django 5.0.4 on 2024-04-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ADDED', 'Создан'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменён')], default='ADDED', max_length=20),
        ),
    ]
