# Generated by Django 5.0.4 on 2024-04-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(through='orders.Order_meal', to='menu.meal', verbose_name='блюда'),
        ),
        migrations.AlterField(
            model_name='order_meal',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal', verbose_name='Блюдо'),
        ),
    ]
