# Generated by Django 5.0.4 on 2024-04-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_alter_order_meals_alter_order_meal_meal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_meal',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='order_meal',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='order_meal',
            unique_together={('order', 'meal')},
        ),
    ]
